### ISSUE TITLE
Mikro OLED B Click...

### ISSUE THREAD

**Issue by kitplummer** [pappersverk/oled#7]
Heyo, have used this module before for another OLED and it's great!  This and chisel are a powerful combo.

But this sucka: https://www.mikroe.com/oled-b-click

Doesn't seem to want to load if I put in the 96x39px dimensions.  Figure it is the odd 39px height.  So if I set it to 38, or 32 it kind of works.  Any chance this is something I doing wrong, easy?

TIA.
Kit

**Comment by luisgabrielroldan** [comment]
Hi! Glad to hear you like those projects :).

About your issue I think this is indeed related to the weird 39 pixels.

The driver uses the height to initialize the display multiplex ratio (set to height - 1) so maybe the problem comes from that side.

Also googling about similar situations I found this with the OLED W model: https://medium.com/electronza/arduino-code-for-oled-w-click-3bade69c726f

In the 5th paragraph the author mentions that he had to use 40px on height.

I'm not sure what is the situation here, but 96x39 doesn't looks really like an standard resolution.

You can try with something like 96x64 so you can address all the pixeles.

Tell me if that works!
Regards.

**Comment by kitplummer** [comment]
Def something in the setting of the dimensions/resolution.  I finally was able to get something working, good enough by setting it to 128x40.  So that leads me to believe there's some kind of offset happening too.  But I have what I need.  :D
